name: Publish to npm 

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  npm-publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: rm *.test.js
      - run: rm -rf .github
      - run: |-
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG/v/}
          cat package.json | jq --arg version $VERSION '. + {"version": $version}' > versioned-package.json
          mv versioned-package.json package.json
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
